### ISSUE TITLE
where example code?

### ISSUE THREAD

**Issue by astranavt** [miduga/react-slidy#12]

**Comment by balazsorban44** [comment]
Trying to figure out myself how to use it. @miduga Could you please provide some information? I tried: 

```
import ReactSlidy from 'react-slidy'
...
<ReactSlidy>
    <img src="https://www.fillmurray.com/460/300" />
    <img src="https://www.fillmurray.com/460/300" />
    <img src="https://www.fillmurray.com/460/300" />
</ReactSlidy>
```

But only the first picture shows up, without any control. It is like a static image. Though I see the structure in the HTML file. Is there a function or something one has to call to initialize it? Thanks


PS: Your example link at: http://miduga.es/projects/react-slidy/ is broken.

**Comment by midudev** [comment]
Hi guys! I'll work this weekend on the slider in order to fix the demo page and also fixing some issues. I'll let you know :)

**Comment by midudev** [comment]
Hi guys! Working on the new slider with a URL with the demo: http://react-slidy-demo.surge.sh/

That's the PR: https://github.com/miduga/react-slidy/pull/13

**Comment by schuylermk** [comment]
@balazsorban44 Did you ever figure out how to import this, or get it working in general?

**Comment by balazsorban44** [comment]
Hi @schuylermk, I went with [react-slick](https://github.com/akiran/react-slick) instead

**Comment by midudev** [comment]
Hey guys! Just pointing that the docs are live now! https://react-slidy.midu.dev
